<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
   <LangVersion>preview</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader.Core">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader.Unity">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Preloader.Unity.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Unity.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Elin">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Elin.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\Mono.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.ActorSystem">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.ActorSystem.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.BaseCore">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.BaseCore.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.Modding">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.Modding.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.Sound">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.Sound.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.UI">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.UI.dll</HintPath>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\SemanticVersioning.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="YKFramework">
      <HintPath>F:\SteamLibrary\steamapps\workshop\content\2135150\3400020753\YKFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y &quot;$(TargetDir)SpecificPortraits.dll&quot; &quot;F:\SteamLibrary\steamapps\common\Elin\Package\Mod_Specific_Portraits&quot;" />
  </Target>

</Project>
