<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
   <LangVersion>preview</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\BepInEx\core\BepInEx.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Elin">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Elin.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.ActorSystem">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.ActorSystem.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.BaseCore">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.BaseCore.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.Modding">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.Modding.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.Sound">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.Sound.dll</HintPath>
    </Reference>
    <Reference Include="Plugins.UI">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\Plugins.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Elin\Elin_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="YKFramework">
      <HintPath>F:\SteamLibrary\steamapps\workshop\content\2135150\3400020753\YKFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
	
</Project>
